name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ 7.4, 8.2 ]
        flavor: [ apache, cli ]

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.version }}/${{ matrix.flavor }}
          load: true
          tags: openmage-dev:${{ matrix.version }}-${{ matrix.flavor }}
      -
        name: Test
        run: |
          docker run --rm -v $(pwd)/test:/app openmage-dev:${{ matrix.version }}-${{ matrix.flavor }} php /app/test.php
      -
        name: Scan for vulnerabilities
        id: scan
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: openmage-dev:${{ matrix.version }}-${{ matrix.flavor }}
          dockerfile: ./${{ matrix.version }}/${{ matrix.flavor }}/Dockerfile
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Push image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.version }}/${{ matrix.flavor }}
          push: true
          tags: ghcr.io/colinmollenhour/docker-openmage-dev:${{ matrix.version }}-${{ matrix.flavor }}
          cache-from: type=registry,ref=colinmollenhour/docker-openmage-dev:${{ matrix.version }}-${{ matrix.flavor }}
          cache-to: type=inline
